# Pandas I — Series & DataFrames

**Objective:** Load, inspect, select, filter and analyze tabular data.

In [1]:
import pandas as pd
import numpy as np

## 1. Create/load a sales dataset

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)

raw_sales = pd.DataFrame({
    "order_id": range(1001, 1016),
    "date": [
        "2026-01-03", "2026-01-05", "2026-01-07", "2026-01-08", "2026-01-12",
        "2026-01-15", "2026-01-18", "2026-01-20", "2026-01-22", "2026-01-25",
        "2026-01-27", "2026-01-29", "2026-02-02", "2026-02-04", "2026-02-06"
    ],
    "region": ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore",
               "Karachi", "Islamabad", "Karachi", "Lahore", "Islamabad",
               "Karachi", "Lahore", "Karachi", "Islamabad", "Lahore"],
    "product": ["Laptop", "Phone", "Tablet", "Headphones", "Laptop",
                "Phone", "Tablet", "Laptop", "Headphones", "Phone",
                "Tablet", "Laptop", "Phone", "Headphones", "Laptop"],
    "quantity": [2, 3, 1, 5, 2, 4, 2, 1, 6, 3, 2, 1, 5, 4, 2],
    "unit_price": [120000, 65000, 45000, 8000, 120000, 65000, 45000, 120000,
                   8000, 65000, 45000, 120000, 65000, 8000, 120000],
    "customer_rating": [4.5, 4.0, np.nan, 4.2, 4.8, 3.9, 4.1, np.nan,
                        4.4, 3.8, 4.6, 4.7, 4.0, 4.3, np.nan]
})
raw_sales["revenue"] = raw_sales["quantity"] * raw_sales["unit_price"]
raw_sales.head()

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue
0,1001,2026-01-03,Karachi,Laptop,2,120000,4.5,240000
1,1002,2026-01-05,Lahore,Phone,3,65000,4.0,195000
2,1003,2026-01-07,Islamabad,Tablet,1,45000,NaN,45000
3,1004,2026-01-08,Karachi,Headphones,5,8000,4.2,40000
4,1005,2026-01-12,Lahore,Laptop,2,120000,4.8,240000

## 2. Series and DataFrame basics

In [4]:
sales = raw_sales.copy()

region_series = sales["region"]
print("Series type:", type(region_series))
print("DataFrame shape:", sales.shape)
print("Columns:", sales.columns.tolist())
print("Index:", sales.index)

Series type: <class 'pandas.Series'>
DataFrame shape: (15, 8)
Columns: ['order_id', 'date', 'region', 'product', 'quantity', 'unit_price', 'customer_rating', 'revenue']
Index: RangeIndex(start=0, stop=15, step=1)

## 3. Inspecting the data

In [5]:
print(sales.head())
print("\nInfo:")
sales.info()
print("\nDescribe:")
display(sales.describe(include="all"))

   order_id        date     region     product  quantity  unit_price  \
0      1001  2026-01-03    Karachi      Laptop         2      120000
1      1002  2026-01-05     Lahore       Phone         3       65000
2      1003  2026-01-07  Islamabad      Tablet         1       45000
3      1004  2026-01-08    Karachi  Headphones         5        8000
4      1005  2026-01-12     Lahore      Laptop         2      120000

   customer_rating  revenue
0              4.5   240000
1              4.0   195000
2              NaN    45000
3              4.2    40000
4              4.8   240000

Info:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15 non-null     int64
 1   date             15 non-null     str
 2   region           15 non-null     str
 3   product          15 non-null     str
 4   quantity         15 non-null     int64
 5   unit_price       15 non-null     int64
 6   customer_rating  12 non-null     float64
 7   revenue          15 non-null     int64
dtypes: float64(1), int64(4), str(3)
memory usage: 1.1 KB

Describe:

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue
count,15.000000,15,15,15,15.000000,15.000000,12.000000,15.000000
unique,NaN,15,3,4,NaN,NaN,NaN,NaN
top,NaN,2026-01-03,Karachi,Laptop,NaN,NaN,NaN,NaN
freq,NaN,1,6,5,NaN,NaN,NaN,NaN
mean,1008.000000,NaN,NaN,NaN,2.866667,67933.333333,4.275000,152000.000000
std,4.472136,NaN,NaN,NaN,1.597617,43047.260850,0.327872,95419.375092
min,1001.000000,NaN,NaN,NaN,1.000000,8000.000000,3.800000,32000.000000
25%,1004.500000,NaN,NaN,NaN,2.000000,45000.000000,4.000000,69000.000000
50%,1008.000000,NaN,NaN,NaN,2.000000,65000.000000,4.250000,120000.000000
75%,1011.500000,NaN,NaN,NaN,4.000000,120000.000000,4.525000,240000.000000
max,1015.000000,NaN,NaN,NaN,6.000000,120000.000000,4.800000,325000.000000

## 4. loc and iloc

In [6]:
print("loc rows 0:3:")
display(sales.loc[0:3, ["order_id", "product", "revenue"]])

print("iloc rows 0:3:")
display(sales.iloc[0:3, 0:4])

loc rows 0:3:

   order_id     product  revenue
0      1001      Laptop   240000
1      1002       Phone   195000
2      1003      Tablet    45000
3      1004  Headphones    40000

iloc rows 0:3:

   order_id        date     region product
0      1001  2026-01-03    Karachi  Laptop
1      1002  2026-01-05     Lahore   Phone
2      1003  2026-01-07  Islamabad  Tablet

## 5. Filtering

In [7]:
high_value = sales[sales["revenue"] > 100000]
karachi = sales[sales["region"] == "Karachi"]
laptops = sales[sales["product"] == "Laptop"]

display(high_value)
display(karachi)
display(laptops)

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue
0,1001,2026-01-03,Karachi,Laptop,2,120000,4.5,240000
1,1002,2026-01-05,Lahore,Phone,3,65000,4.0,195000
4,1005,2026-01-12,Lahore,Laptop,2,120000,4.8,240000
5,1006,2026-01-15,Karachi,Phone,4,65000,3.9,260000
7,1008,2026-01-20,Karachi,Laptop,1,120000,NaN,120000
9,1010,2026-01-25,Islamabad,Phone,3,65000,3.8,195000
11,1012,2026-01-29,Lahore,Laptop,1,120000,4.7,120000
12,1013,2026-02-02,Karachi,Phone,5,65000,4.0,325000
14,1015,2026-02-06,Lahore,Laptop,2,120000,NaN,240000

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue
0,1001,2026-01-03,Karachi,Laptop,2,120000,4.5,240000
3,1004,2026-01-08,Karachi,Headphones,5,8000,4.2,40000
5,1006,2026-01-15,Karachi,Phone,4,65000,3.9,260000
7,1008,2026-01-20,Karachi,Laptop,1,120000,NaN,120000
10,1011,2026-01-27,Karachi,Tablet,2,45000,4.6,90000
12,1013,2026-02-02,Karachi,Phone,5,65000,4.0,325000

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue
0,1001,2026-01-03,Karachi,Laptop,2,120000,4.5,240000
4,1005,2026-01-12,Lahore,Laptop,2,120000,4.8,240000
7,1008,2026-01-20,Karachi,Laptop,1,120000,NaN,120000
11,1012,2026-01-29,Lahore,Laptop,1,120000,4.7,120000
14,1015,2026-02-06,Lahore,Laptop,2,120000,NaN,240000

## 6. Adding columns

In [8]:
sales["discount"] = np.where(sales["quantity"] >= 4, 0.10, 0.05)
sales["net_revenue"] = sales["revenue"] * (1 - sales["discount"])

display(sales[["product", "quantity", "revenue", "discount", "net_revenue"]].head())

      product  quantity  revenue  discount  net_revenue
0      Laptop         2   240000      0.05     228000.0
1       Phone         3   195000      0.05     185250.0
2      Tablet         1    45000      0.05      42750.0
3  Headphones         5    40000      0.10      36000.0
4      Laptop         2   240000      0.05     228000.0

## 7. Sorting and indexing

In [9]:
print("Highest revenue:")
display(sales.sort_values("revenue", ascending=False).head())

print("Highest quantity:")
display(sales.sort_values("quantity", ascending=False).head())

Highest revenue:

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue,discount,net_revenue
12,1013,2026-02-02,Karachi,Phone,5,65000,4.0,325000,0.10,292500.0
5,1006,2026-01-15,Karachi,Phone,4,65000,3.9,260000,0.10,234000.0
4,1005,2026-01-12,Lahore,Laptop,2,120000,4.8,240000,0.05,228000.0
14,1015,2026-02-06,Lahore,Laptop,2,120000,NaN,240000,0.05,228000.0
0,1001,2026-01-03,Karachi,Laptop,2,120000,4.5,240000,0.05,228000.0

Highest quantity:

,order_id,date,region,product,quantity,unit_price,customer_rating,revenue,discount,net_revenue
8,1009,2026-01-22,Lahore,Headphones,6,8000,4.4,48000,0.1,43200.0
12,1013,2026-02-02,Karachi,Phone,5,65000,4.0,325000,0.1,292500.0
3,1004,2026-01-08,Karachi,Headphones,5,8000,4.2,40000,0.1,36000.0
5,1006,2026-01-15,Karachi,Phone,4,65000,3.9,260000,0.1,234000.0
13,1014,2026-02-04,Islamabad,Headphones,4,8000,4.3,32000,0.1,28800.0

## 8. Ten insights

In [10]:
insights = [
    f"1. Dataset contains {len(sales)} orders.",
    f"2. Dataset has {sales['product'].nunique()} unique products.",
    f"3. Dataset covers {sales['region'].nunique()} regions.",
    f"4. Total revenue is Rs. {sales['revenue'].sum():,.0f}.",
    f"5. Average order revenue is Rs. {sales['revenue'].mean():,.0f}.",
    f"6. Highest single-order revenue is Rs. {sales['revenue'].max():,.0f}.",
    f"7. Total quantity sold is {sales['quantity'].sum()} units.",
    f"8. Most frequently sold product is {sales['product'].value_counts().idxmax()}.",
    f"9. Region with the most orders is {sales['region'].value_counts().idxmax()}.",
    f"10. Average customer rating is {sales['customer_rating'].mean():.2f}."
]
print("\n".join(insights))

1. Dataset contains 15 orders.
2. Dataset has 4 unique products.
3. Dataset covers 3 regions.
4. Total revenue is Rs. 2,280,000.
5. Average order revenue is Rs. 152,000.
6. Highest single-order revenue is Rs. 325,000.
7. Total quantity sold is 43 units.
8. Most frequently sold product is Laptop.
9. Region with the most orders is Karachi.
10. Average customer rating is 4.27.

## Conclusion

Pandas provides high-level tabular data structures and expressive indexing, filtering and inspection operations that form the foundation of practical data analysis.